# Generated by Django 5.1.1 on 2024-09-18 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoprocessing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtitle',
            name='file_format',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='subtitle',
            name='subtitle_type',
            field=models.CharField(blank=True, choices=[('extracted', 'Extracted'), ('generated', 'Generated')], max_length=10, null=True),
        ),
    ]
