# Generated by Django 5.1.1 on 2024-09-18 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoprocessing', '0002_subtitle_file_format_subtitle_subtitle_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtitle',
            name='video_file',
        ),
        migrations.AddField(
            model_name='subtitle',
            name='video_file_name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
