# Generated by Django 5.1.1 on 2024-09-18 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoprocessing', '0005_subtitle_subtitle_name_ext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtitle',
            name='subtitle_name_ext',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
